(function () {
  "use strict";

  const engine = window.IamLab;
  const sources = [
    ["IAM identities: users, groups, and roles", "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_identity-management.html"],
    ["IAM security best practices", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"],
    ["Policy evaluation and deny precedence", "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html"],
    ["S3 console access and prefix conditions", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/walkthrough1.html"],
    ["Account principals in trust policies", "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html"],
    ["Permission to switch roles", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_permissions-to-switch.html"],
    ["Switch roles in the console", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-console.html"],
    ["MFA conditions for role trust", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html"],
    ["Roles for EC2 applications", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html"],
    ["Associating a role with an EC2 instance", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/attach-iam-role.html"],
    ["Temporary role credentials on EC2", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-security-credentials.html"],
    ["Session Manager prerequisites", "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-prerequisites.html"]
  ];

  function escape(value) {
    return String(value).replace(/[&<>"']/g, function (character) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]; });
  }

  function link(url, title) {
    return '<a href="' + escape(url) + '" target="_blank" rel="noopener noreferrer">' + title + " ↗</a>";
  }

  function bundle(config) {
    return {
      LabReadTraining: engine.readerPolicy(config.bucket),
      LabUploadTraining: engine.uploadPolicy(config.bucket),
      LabUploaderTrust: engine.trustPolicy(config.account, "lab-learner"),
      LabAssumeUploader: engine.assumePolicy(config.account, "lab-uploader"),
      LabEC2ReadTraining: engine.ec2ReadPolicy(config.bucket),
      LabEC2Trust: engine.ec2TrustPolicy()
    };
  }

  function codeBlock(id, title, policy, configured) {
    return '<div class="code-block"><div class="panel-title"><h3>' + title + '</h3><button type="button" class="secondary small-button" data-copy="' + id + '"' + (!configured ? " disabled" : "") + '>Copy JSON</button></div><pre><code id="' + id + '">' + escape(JSON.stringify(policy, null, 2)) + "</code></pre></div>";
  }

  function step(index, title, content, config, open) {
    return '<details class="panel aws-step"' + (open ? " open" : "") + '><summary>' + String(index + 1).padStart(2, "0") + " / " + title + '<small>' + (config.done.includes(index) ? "✓ checked" : "") + "</small></summary>" + content + window.IamVisuals.card(window.IamVisuals.awsSteps[index], { compact: true }) + '<div class="complete-step"><label class="check-label"><input type="checkbox" data-aws-step="' + index + '"' + (config.done.includes(index) ? " checked" : "") + '><span>I completed this step in AWS.</span></label></div></details>';
  }

  function render(config, matrixState = engine.freshMatrixState()) {
    const configured = Boolean(config.account && config.bucket);
    const values = configured ? config : { account: "123456789012", bucket: "your-unique-lab-bucket" };
    const policies = bundle(values);
    const bucket = escape(values.bucket);
    const roleUrl = "https://signin.aws.amazon.com/switchrole?account=" + values.account + "&roleName=lab-uploader";
    const intro = '<div class="eyebrow">THE HANDS-ON AWS LAB</div><h1>Now build it in your account.</h1><p class="intro aws-intro">Create a real IAM user, a group, two permission sets, and an assumable role. Then verify allowed and denied requests against a small S3 practice bucket.</p><div class="meta-row"><span class="chip">GUIDED CONSOLE PRACTICE</span><span class="chip">About 45–60 minutes</span><span class="chip">8 core steps + EC2 and multi-user extensions</span></div><div class="callout"><strong>You perform these steps in the AWS console.</strong> This lab page generates policy text and saves your checklist locally; it does not connect to AWS or verify live resources. IAM has no additional charge; S3 storage and requests can incur small charges. Use tiny practice files and finish the cleanup. ' + link("https://aws.amazon.com/s3/pricing/", "S3 pricing") + '</div>';
    const setup = '<section class="panel"><div class="panel-title"><h2>Personalize your policies</h2><span>Commercial AWS accounts</span></div><p class="lesson-copy">Find your 12-digit account ID in the AWS console account menu. Pick a globally unique bucket name using lowercase letters, numbers, and hyphens. These values are saved only in this browser.</p><form id="aws-config-form"><div class="aws-config"><div class="form-field"><label for="aws-account">AWS account ID</label><input type="text" id="aws-account" value="' + escape(config.account) + '" placeholder="123456789012" pattern="[0-9]{12}" maxlength="12" inputmode="numeric" required autocomplete="off"></div><div class="form-field"><label for="aws-bucket">Your new lab bucket name</label><input type="text" id="aws-bucket" value="' + escape(config.bucket) + '" placeholder="iam-field-lab-your-unique-suffix" pattern="[a-z0-9][a-z0-9\\-]{1,61}[a-z0-9]" minlength="3" maxlength="63" required autocomplete="off"></div></div><button type="submit" class="primary">Generate my policy documents</button></form>' + (!configured ? '<p class="help">Example values appear below. Enter your own values to enable copying and downloading.</p>' : '<p class="help">Policy documents now use your account and bucket. Regenerating clears the checklist. Fixed IAM names: lab-learner, lab-readers, and lab-uploader.</p>') + '</section>';
    const prepare = step(0, "Prepare your practice bucket", '<ol><li>Sign in to a <strong>practice account using an existing administrator identity</strong>, preferably through IAM Identity Center. You need permission to create and remove the lab IAM resources and S3 bucket. Use fresh lab resources; keep your administrator session available.</li><li>Open ' + link("https://s3.console.aws.amazon.com/s3/home", "S3") + ' → <strong>Create bucket</strong>. Use <code>' + bucket + '</code>. Choose a general purpose bucket in a region such as Singapore (<code>ap-southeast-1</code>).</li><li>Keep <strong>Block all public access on</strong>, ACLs disabled (Bucket owner enforced), and versioning off. Use <strong>SSE-S3</strong> encryption so this lesson does not require KMS permissions. Leave other optional features off.</li><li>Create the folder <code>training</code>. Inside it, upload ' + link("samples/welcome.txt", "welcome.txt") + '. Create a nested folder <code>uploads</code> and upload ' + link("samples/starter.txt", "starter.txt") + ' there. Create the root folder <code>private</code> and upload ' + link("samples/notes.txt", "notes.txt") + ' there. You may use any tiny text files with those names.</li></ol><pre><code>' + bucket + '/\n├── training/\n│   ├── welcome.txt\n│   └── uploads/\n│       └── starter.txt\n└── private/\n    └── notes.txt</code></pre><p class="help">S3 folders are key prefixes. The actual object keys include the folder names. This practice layout keeps actual file contents out of the bucket root.</p>', config, true);
    const user = step(1, "Create the IAM user and enrol MFA", '<ol><li>As your administrator, open ' + link("https://console.aws.amazon.com/iam/home#/users", "IAM → Users") + ' → <strong>Create user</strong>. Name it <code>lab-learner</code>.</li><li>Select <strong>Provide user access to the AWS Management Console</strong>, then <strong>I want to create an IAM user</strong> if prompted. Set a strong password using the console. Keep it in your password manager, and keep password reset at first sign-in enabled.</li><li>Create the user without S3 or administrator permissions. If AWS adds <code>IAMUserChangePassword</code> for first sign-in, keep it; it does not grant S3 access. If your account handles password changes differently, have the administrator grant the required self-password-change permission before first sign-in.</li><li>From the administrator session, open the new user → <strong>Security credentials → Assign MFA device</strong>. Enrol your authenticator or security key. This is administrator-assisted setup, so the learner does not need IAM administration permissions.</li><li>Record the account sign-in URL. Use a <strong>separate browser profile or private window</strong> to sign in as <code>lab-learner</code>, change its initial password, and authenticate with MFA. Keep this window separate from your administrator session.</li></ol><div class="callout">Create no access keys. The lab uses console sign-in and role sessions. Enter passwords and MFA codes only into AWS or your authenticator, never into this lab page.</div><p>At this point, S3 access is denied: creating an identity is not the same as granting permission.</p>', config);
    const group = step(2, "Create the group and add the learner", '<ol><li>Back in the administrator session, open <strong>IAM → User groups → Create group</strong>.</li><li>Name it <code>lab-readers</code>. Select <code>lab-learner</code> as a member. Do not attach a broad managed policy such as ReadOnlyAccess or AdministratorAccess.</li><li>Create the group. Open its <strong>Users</strong> tab and confirm the learner is a member.</li></ol><p>A user group is a permissions-management tool. You cannot sign in as a group or use a group as a role’s trusted principal.</p>', config);
    const reader = step(3, "Create and attach the restricted policy", '<ol><li>Open <strong>IAM → Policies → Create policy → JSON</strong>. Replace the editor contents with the following complete document.</li><li>Review the resource ARNs, create the customer managed policy, and name it <code>LabReadTraining</code>.</li><li>Open <strong>IAM → User groups → lab-readers → Permissions → Add permissions → Attach policies</strong>. Attach <code>LabReadTraining</code>.</li></ol>' + codeBlock("aws-reader-json", "LabReadTraining · attach to lab-readers", policies.LabReadTraining, configured) + '<p><strong>What it does:</strong> reads objects only under <code>training/*</code>, restricts listing to the training prefix plus root folder navigation, and explicitly denies deletion of lab objects.</p><div class="callout">The console also needs navigation permissions. <code>ListAllMyBuckets</code> exposes bucket names, and root listing exposes top-level folder names. Those permissions do not allow reading private file contents. <code>ListBucket</code> uses a bucket ARN; <code>GetObject</code> uses an object ARN.</div>', config);
    const test = step(4, "Verify the user's restricted access", '<p>Use the learner’s browser window. Refresh after IAM changes; propagation may take a little time. Verify which identity is shown in the top-right account menu.</p><div class="table-wrap"><table><thead><tr><th>Try as lab-learner</th><th>Expected</th><th>Reason</th></tr></thead><tbody><tr><td>Open training/ and download welcome.txt</td><td>Allowed</td><td>ReadTraining matches the object ARN.</td></tr><tr><td>Open private/</td><td>Denied</td><td>ListBucket prefix condition does not match.</td></tr><tr><td>Upload a tiny file into training/uploads/</td><td>Denied</td><td>No Allow for PutObject.</td></tr><tr><td>Delete training/uploads/starter.txt</td><td>Denied</td><td>ProtectLabObjects explicitly denies DeleteObject.</td></tr></tbody></table></div><p>For an exact private-file read test, use the administrator’s ' + link("https://policysim.aws.amazon.com/", "IAM Policy Simulator") + ': select <code>lab-learner</code>, Amazon S3, and <code>GetObject</code>. In the action’s resource settings, enter <code>arn:aws:s3:::' + bucket + '/private/notes.txt</code>, then run the simulation. Expected: denied. Compare with <code>arn:aws:s3:::' + bucket + '/training/welcome.txt</code>, which should be allowed.</p><p class="help">The AWS simulator helps inspect policies; it does not perform an S3 operation or prove the object exists. Testing role trust still needs the actual switch-role step.</p><details><summary>If the result is unexpected</summary><p>Check the exact bucket name, object key, group membership, attached policy, and active identity. For listing simulations, provide both s3:prefix and s3:delimiter context. A missing object, an organization SCP, a permissions boundary, bucket policy, or KMS encryption can change real results. Other S3 console panels may show denied operations outside this lesson’s permissions.</p></details>', config);
    const role = step(5, "Create the role, trust, and caller permission", '<p>A role needs <strong>permissions</strong> describing what a session can do, and <strong>trust</strong> describing who may request that session. This lab also grants the caller permission to request the role.</p><ol><li>As administrator, create another customer managed policy named <code>LabUploadTraining</code> using the role permissions below.</li><li>Open <strong>IAM → Roles → Create role → Custom trust policy</strong>. Replace the trust editor contents with <code>LabUploaderTrust</code> below.</li><li>In the permissions step, attach <code>LabUploadTraining</code>. Name the role <code>lab-uploader</code> and create it. The default maximum session duration is sufficient.</li><li>Create a customer managed policy named <code>LabAssumeUploader</code> from the final document below, then attach it to the <code>lab-readers</code> group.</li></ol>' + codeBlock("aws-upload-json", "LabUploadTraining · role permissions", policies.LabUploadTraining, configured) + codeBlock("aws-trust-json", "LabUploaderTrust · role trust relationship", policies.LabUploaderTrust, configured) + codeBlock("aws-assume-json", "LabAssumeUploader · attach to lab-readers", policies.LabAssumeUploader, configured) + '<div class="callout">In this trust policy, <code>arn:aws:iam::' + escape(values.account) + ':root</code> means the account principal. The <code>aws:PrincipalArn</code> condition narrows it to <code>lab-learner</code>; the Bool condition requires an MFA-authenticated user session. This account-delegation pattern also needs the caller’s <code>sts:AssumeRole</code> permission.</div><p class="help">Trust policies live on roles; do not create the trust document as a standalone managed permissions policy. Some other same-account trust patterns can grant permission directly, which is why “both policies are always required” is too broad a rule.</p>', config);
    const assume = step(6, "Switch role and test the new session", '<ol><li>In the learner’s MFA-authenticated session, choose the identity menu → <strong>Switch role</strong>. With multi-session support, use <strong>Add session → Switch role</strong>. Enter account <code>' + escape(values.account) + '</code> and role <code>lab-uploader</code>. ' + (configured ? link(roleUrl, "Open the prefilled switch-role page") : "Generate your policies to get a prefilled switch-role link.") + '</li><li>Verify the account menu now shows the role. Open the lab bucket, then <code>training/uploads/</code>. Upload a small new file named <code>notes.txt</code>, leaving optional tags and ACL settings alone. Expected: <strong>success</strong>.</li><li>Download <code>training/uploads/starter.txt</code>. Expected: <strong>success</strong>. Try downloading <code>training/welcome.txt</code>. Expected: <strong>denied</strong>, because the role can read only the uploads prefix.</li><li>Try deleting <code>training/uploads/notes.txt</code>. Expected: <strong>explicitly denied</strong> by the role’s own ProtectLabObjects statement.</li><li>Choose the identity menu → <strong>Switch back</strong> (or select the original learner session). Upload is denied again; reading <code>training/welcome.txt</code> works again.</li></ol><p><strong>Explain it:</strong> role sessions use the role’s permissions. The user’s existing group permissions are not added to them. MFA enrolment alone is insufficient: the learner must have signed in using MFA. If you enrolled MFA after signing in, sign out and sign back in before switching.</p><details><summary>Optional experiment: remove group membership</summary><p>As administrator, temporarily remove lab-learner from lab-readers. Fresh user requests lose its group permissions, and new role-assumption attempts fail. An already-issued role session can remain valid, so first switch back before testing the caller. Add the user back afterward.</p></details>', config);
    const cleanup = step(7, "Clean up the lab", '<ol><li>Switch back from the role, then sign out of the learner session. Use your administrator session for cleanup; both lab policies intentionally deny deletion.</li><li>In S3, open only <code>' + bucket + '</code>, choose <strong>Empty</strong>, verify the bucket name, and empty it. Then delete that bucket. If you enabled versioning despite the instructions, remove versions and delete markers too.</li><li>In IAM, open <code>lab-learner</code>, deactivate its MFA device, remove its lab sign-in credentials, and delete the user. Delete the unused virtual MFA device if one was created; remove its authenticator entry after it is deactivated.</li><li>Detach <code>LabReadTraining</code> and <code>LabAssumeUploader</code> from <code>lab-readers</code>, then delete the empty group.</li><li>Detach <code>LabUploadTraining</code> from <code>lab-uploader</code>, then delete the role.</li><li>Delete the three customer managed policies: <code>LabReadTraining</code>, <code>LabUploadTraining</code>, and <code>LabAssumeUploader</code>. The trust policy disappears with the role. Leave AWS managed policies such as IAMUserChangePassword in place.</li><li>Remove any local copies of the learner’s password. Confirm the named bucket, user, group, role, and customer managed policies are gone.</li></ol><p class="help">Checking this box is your own completion record. Restarting the simulator never removes AWS resources.</p>', config);
    return intro + '<div class="button-row"><button type="button" class="secondary" data-open-aws-matrix>Jump to the independent multi-user lab →</button></div>' + setup + '<div class="aws-notes"><p id="aws-count">' + config.done.length + ' / 8 steps checked</p><button class="secondary small-button" type="button" data-download' + (!configured ? " disabled" : "") + '>Download policy reference bundle</button></div><p class="help">The reference bundle contains six separately labelled documents. In IAM, paste each individual policy using its Copy JSON button; the whole bundle is not one IAM policy.</p>' + prepare + user + group + reader + test + role + assume + window.IamEc2Lesson.renderAws(config, { codeBlock: codeBlock, link: link, escape: escape }) + window.IamMatrixLesson.renderAws(config.matrix || { a: "", b: "", shared: "", done: [] }, matrixState, { codeBlock: codeBlock, link: link, escape: escape }) + cleanup + '<section class="panel" style="margin-top:20px"><h2>Official AWS references</h2><ul class="source-list">' + sources.map(function (source) { return "<li>" + link(source[1], source[0]) + "</li>"; }).join("") + '</ul><p class="help">Console labels can change. Use the equivalent IAM Users, User groups, Policies, Roles, and S3 pages if your layout differs. This lab targets the standard aws partition.</p></section>';
  }

  window.IamAwsGuide = { render: render, bundle: bundle };
})();
